### PR TITLE
removed the mock data

### PR DESCRIPTION
**Pull request by anurag-a1975**
please do the review

### CODE REVIEW

**Review by anuragabc — APPROVED** [review]
ok

**Review by ganura123 — COMMENTED** [review]
ok, i feel it should have been better.

**Comment by anurag-a1975** [comment]
@ganura123 this is because of xyz reason.

**Review by ganura123 — CHANGES_REQUESTED** [review]
lets add the comment that you have removed the mock data.

**Review by ganura123 — APPROVED** [review]

**Pull request merged**
